services:
  military-war:
    build:
      context: .
      dockerfile: Dockerfile
    image: military-war:latest
    container_name: military-war
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
